apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: "SSO project"
    openshift.io/display-name: "Red Hat SSO"
  name: keycloak
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
  name: sso
  namespace: keycloak
spec:
  targetNamespaces:
    - keycloak
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhsso-operator
  namespace: keycloak
spec:
  channel: alpha
  installPlanApproval: Manual
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---